apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
  - certificate.yaml
  - kafka.yaml
  - redis.yaml
  - secret.yaml
  - ip-visit-counter/app.yaml
  - ip-visit-consumer/app.yaml
  - ip-info/app.yaml
  - ip-visit-frontend/app.yaml