apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: ip-visit-info
spec:
  selector:
    matchLabels:
      app: "ip-visit-info"
  replicas: 1
  template:
    metadata:
      labels:
        app: ip-visit-info
    spec:
      containers:
      - name: main
        image: ghcr.io/metalbear-co/playground-ip-visit-info:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
        - name: PORT
          value: "80"


---

apiVersion: v1
kind: Service
metadata:
  name: ip-info
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: ip-info