apiVersion: v1
kind: Service
metadata:
  name: ip-visit-counter
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: ip-visit-counter

---

apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: ip-visit-counter
spec:
  selector:
    matchLabels:
      app: "ip-visit-counter"
  replicas: 1
  template:
    metadata:
      labels:
        app: ip-visit-counter
    spec:
      containers:
      - name: main
        image: ghcr.io/metalbear-co/playground-ip-visit-counter:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
        - name: PORT
          value: "80"
        - name: REDISADDRESS
          value: "redis-main:6379"
        - name: RESPONSEFILE
          value: "/app/response.txt"
        - name: KAFKAADDRESS
          value: "kafka-service:9092"
        - name: KAFKATOPIC
          value: "ip-visit"
        - name: IPINFOADDRESS
          value: "http://ip-info"
        - name: IPINFOGRPCADDRESS
          value: "ip-info-grpc:5001"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
              optional: true
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
              optional: true