apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- redis.yaml
- ip-visit-counter.yaml
- ip-visit-consumer.yaml
- ip-info.yaml
- ip-info-grpc.yaml

helmCharts:
- name: kafka
  valuesInline:
    listeners:
      client:
        protocol: 'PLAINTEXT'
      controller:
        protocol: 'PLAINTEXT'
  releaseName: kafka
  version: 32.2.0
  repo: oci://registry-1.docker.io/bitnamicharts