apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: ip-visit-frontend
spec:
  selector:
    matchLabels:
      app: "ip-visit-frontend"
  replicas: 1
  template:
    metadata:
      labels:
        app: ip-visit-frontend
    spec:
      containers:
      - name: main
        image: ghcr.io/metalbear-co/playground-ip-visit-frontend:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
        - name: PORT
          value: "3000"


---

apiVersion: v1
kind: Service
metadata:
  name: ip-visit-frontend
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: ip-visit-frontend