apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
  - certificate.yaml
  - secret.yaml
  - ip-visit-frontend.yaml
  - ../reusables/sqs-specific

patches:
- path: aws-creds-patch.yaml
  target:
    kind: Deployment
    name: ip-visit-counter
- path: aws-creds-patch.yaml
  target:
    kind: Deployment
    name: ip-visit-sqs-consumer
