apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
  - certificate.yaml
  - secret.yaml
  - ip-visit-frontend.yaml
  - ip-visit-sqs-consumer.yaml
  - sqs-queueregistry.yaml