apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: ip-visit-consumer
spec:
  selector:
    matchLabels:
      app: "ip-visit-consumer"
  replicas: 1
  template:
    metadata:
      labels:
        app: ip-visit-consumer
    spec:
      containers:
      - name: main
        image: ghcr.io/metalbear-co/playground-ip-visit-consumer:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
        - name: PORT
          value: "80"
        - name: KAFKAADDRESS
          value: "kafka-service:9092"
        - name: KAFKATOPIC
          value: "ip-visit"
        - name: KAFKACONSUMERGROUP
          value: "ip-visit-consumer"
