apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirrord-operator
  namespace: mirrord
spec:
  template:
    spec:
      containers:
      - name: mirrord-operator
        env:
        - name: AWS_ENDPOINT_URL
          value: "http://localstack.localstack.svc.cluster.local:4566"
        - name: AWS_SECRET_ACCESS_KEY
          value: "test"
        - name: AWS_ACCESS_KEY_ID
          value: "test"