name: Release ip visit counter
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ip-visit-counter/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          context: ./
          push: true
          tags: |
            ghcr.io/metalbear-co/playground-ip-visit-counter:latest
            ghcr.io/metalbear-co/playground-ip-visit-counter:${{ github.sha }}